default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: setlist-backend_development
  username: <%=  ENV['DB_USERNAME'] %>
  password: <%=  ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: setlist-backend_test
  username: <%=  ENV['DB_USERNAME'] %>
  password: <%=  ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: setlist-backend_production
  username: setlist-backend
  password: <%= ENV['SETLIST-BACKEND_DATABASE_PASSWORD'] %>
